### ISSUE TITLE
应减少重复的代码

### ISSUE THREAD

**Issue by osdodo** [Viskeyy/10fund#1]
https://github.com/Viskeyy/10fund/blob/07ccbb1415c3849ac52c5d38744afbff8114b08c/components/insight.tsx#L25
https://github.com/Viskeyy/10fund/blob/07ccbb1415c3849ac52c5d38744afbff8114b08c/components/navigator.tsx#L44
https://github.com/Viskeyy/10fund/blob/07ccbb1415c3849ac52c5d38744afbff8114b08c/components/sight.tsx#L18
https://github.com/Viskeyy/10fund/blob/07ccbb1415c3849ac52c5d38744afbff8114b08c/components/team.tsx#L44

**Comment by Viskeyy** [comment]
已修改
